### ISSUE TITLE
yum-cron emits messages even with debuglevel=-4

### ISSUE THREAD

**Issue by troelsarvin** [rpm-software-management/yum#22]
I have enabled yum-cron to make some servers self-maintain as much as possible. But in case they don't, it's not the end of the world (regular manually initiated yum updates will take care of things, in case automation has failed).

Therefore, I don't want to get error mails from yum like this:

```
/etc/cron.hourly/0yum-hourly.cron:

Could not get metalink https://mirrors.fedoraproject.org/metalink?repo=epel-7&arch=x86_64 error was
14: HTTPS Error 503 - Service Unavailable
```

I only ever want to hear from yum-cron, if it runs into rpm database corruption, or something of that severity.

Consequently, I've adjusted /etc/yum/yum-cron-hourly.conf and /etc/yum/yum-cron.conf, so that
emit_via =
debuglevel = -4

Still, I get error mails like the above quoted once in a while. I'm seeing this on some CentOS 7.2 servers. I have seen something similar on RHEL servers (but on the RHEL servers, I've simply stopped using yum-cron, in order to cut down on mail-noise).

I believe it's due to the _getMetalink method in yum/yumRepo.py. It prints an error message without considering debuglevel. I don't know it is best fixed, though.

A way to reproduce the error:
Adjuste /etc/yum/yum-cron-hourly.conf, asking yum-cron to download updates, but keep silient (see above) with a temporary iptables rule which drops packets to port 443/tcp. Run /etc/cron.hourly/0yum-hourly.cron
(For the sake of testing, it's also nice to have random_sleep=0, so that calling /etc/cron.hourly/0yum-hourly.cron doesn't start by sleeping for a while.)

**Comment by dvershinin** [comment]
+1

**Comment by mikkeljohnsen** [comment]
Yes please fix this. I get 20 email in our bugsystem everytime a metalink error occours.

**Comment by dmnks** [comment]
This is weird. The error message "Could not get metalink ..." is printed via the python print statement (no logging is involved) so there doesn't seem to be a way for it to end up in an email. Unless I'm missing something...

Can you maybe share such an email you got with the message?

**Comment by dmnks** [comment]
OK, I think I got it. You said you set emit_via to an empty value while still getting emails; this is the culprit. It's actually cron that sends out the emails (not yum-cron per se). It does when the `MAILTO` env var is set.

Still, yum should respect the debuglevel setting when printing these errors. Sadly, there's a lot of places in the code base where the simple print statement is used instead of the proper logging function. I think we could replace these prints if it's really needed, but you can stop these emails right now by disabling this cron feature, see:
http://www.putorius.net/2015/03/stop-cron-daemon-from-sending-email-for.html
